### ISSUE TITLE
How should the POST request be made

### ISSUE THREAD

**Issue by ilclaudio** [sbrannstrom/nestjs-passport-ldap-example#15]
Hi,
how should the POST request be made?
I'm trying this without success:

`POST http://localhost:3000/ldap`

with body:

```
{
"username": "myname",
"password": "mypassword"
}
```

**Comment by makeappnetworks** [comment]
> Hi, how should the POST request be made? I'm trying this without success:
> 
> `POST http://localhost:3000/ldap`
> 
> with body:
> 
> ```
> {
> "username": "myname",
> "password": "mypassword"
> }
> ```

Did you succeed?

**Comment by sbrannstrom** [comment]
Hi @ilclaudio and @makeappnetworks. I've updated the repository and improved the example. Check `ldap.strategy.ts` now.

**Comment by sbrannstrom** [comment]
Closing this as the example has been updated and is working as intended.
